version: '3'

services:
  api:
    image: golang:1.15.0-alpine
    volumes:
      - .:/go/src/app
    ports:
      - 33001:3001
    tty: true
    command: >
      sh -c "cd /go/src/app &&
      apk update &&
      apk add --no-cache git &&
      GO111MODULE=off go get -u github.com/codegangsta/gin &&
      go mod init || : &&
      gin -i run"
    environment:
      GO111MODULE: "on"
      POSTGRES_USER: "hitotsu"
      POSTGRES_PASSWORD: "hitotsu"
      POSTGRES_DB: "hitotsu_develop"
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: hitotsu
      POSTGRES_PASSWORD: hitotsu
      POSTGRES_DB: hitotsu_develop
    ports:
      - 35432:5432

