version: '3'

services:
  api:
    image: tetafro/golang-gcc:1.15-alpine
    volumes:
      - .:/go/src/app
    ports:
      - 33001:3001
    tty: true
    command: >
      sh -c "cd /go/src/app &&
      apk update &&
      apk add --no-cache git &&
      GO111MODULE=off go get -u github.com/codegangsta/gin &&
      go get -v github.com/rubenv/sql-migrate/... &&
      go mod init || : &&
      gin -i run"
    environment:
      GO111MODULE: "on"
    env_file:
      - .env
  db:
    image: postgres:alpine
    ports:
      - 35432:5432
    env_file:
      - .env
