version: '3'

services:
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    volumes:
      - .:/go/src/htt-back
    ports:
      - 38080:8080
    tty: true
    command: go run main.go

  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: hitotsu
      POSTGRES_PASSWORD: hitotsu
      POSTGRES_DB: hitotsu_develop
    ports:
      - 35432:5432

